algoritmo "minha idade"
// Função :
// Autor :
// Data : 04/03/2024
// Seção de Declarações 
var
   ano, nasc, idade:inteiro
inicio
// Seção de Comandos 
   escreva("Em que ao estamos: ")
   leia(ano)
   escreva("Em que ano você nasceu?")
   leia(nasc)
   idade<- ano - nasc
   Escreval("Em " , ano, " você terá ",idade, " anos")
   se (idade >=21) entao
   escreval("Então você terá atingido a maior idade")
   
   fimSe


fimalgoritmo
