algoritmo "CreuzaConversor"
// Função :
// Autor :
// Data : 20/03/2024
// Seção de Declarações 
var
     R, D:Real
     Contador:Inteiro
inicio
// Seção de Comandos 
Contador <- 1
Enquanto(Contador <= 4) FACA
                  Escreva("Qual o valor em R$? " )
                  leia(R)
                  D<- R/2,20
                  Escreval(" O valor convertido em U$$ é de: ", D:5:2)
FimEnquanto

fimalgoritmo
